### ISSUE TITLE
FixedGun Update Crash

### ISSUE THREAD

**Issue by zaxhutchinson** [Leading-AI-Development-Solutions/MAIA#22]
Looks like the update method for the FixedGun comp has a rogue parameter. It should just have 'self', not 'cmd'.

https://github.com/Leading-AI-Development-Solutions/MAIA/blob/1d5e02fd9a5420935680e3f0acc1d53d5e92eac0/comp.py#L154-L159

**Comment by zaxhutchinson** [comment]
At least I think so....looking at the other comp update methods.

**Comment by Graham-Berry** [comment]
It seems to me like it does need to take a command argument, as it can either fire or reload? This is causing a crash for you?

**Comment by zaxhutchinson** [comment]
For the component command function, yes, they need to know what command is being given. Not so for the update(), I think. Either way, all comp update functions need to have identical parameter lists otherwise the functional polymorphism won't work.

**Comment by Graham-Berry** [comment]
I see now. Added to bugfix
