### ISSUE TITLE
searchRadarForObjname() related crash

### ISSUE THREAD

**Issue by zaxhutchinson** [Leading-AI-Development-Solutions/MAIA#23]
There seems to be an error(s) in this function in the ai_helpers.py (in case anyone tries to use it in an AI script). I'll diagnose it later tonight and post a fixed version here. Seems to be treating something as a dictionary that isn't one.

I suspect by the end of this script I'll have a beefed up ai_helpers file. Or the beginnings of one.

**Comment by zaxhutchinson** [comment]
I think this fixes the issue. Now returns a list of pings whose name field matches the string parameter. But the previous function level comment had nothing to do with what was being returned. NOTE: I left in the try-except used to debug. But I plan on tackling systematic logging for the whole code base in summer, so this will be replaced with that.

```
##################################
# Search radar view for pings containing specific objnames.
# Returns a list of pings that contain the objname.
#
def searchRadarForObjname(view, name):
    found_pings = []
    comp_views = getSubView(view, "comp")
    try:
        if comp_views is not None:
            radar_views = {}
            for cview in comp_views:
                radar_views = []
                # Find all comp views from radar components
                if cview["ctype"] == "Radar":
                    radar_views.append(cview)

                # Search the radar views for pings with a matching obj name.
                for sv in radar_views:
                    pings = sv["pings"]
                    for p in pings:
                        if p["name"] == name:
                            found_pings.append(p)
    
    except Exception as e:
        traceback.print_exc()
    return found_pings
```

**Comment by Graham-Berry** [comment]
I have added to the pr, with the exception of the try-except. our formatter does not like it for a couple of reasons so I omitted for simplicity.
